In [1]:
#Exp no.:4

In [2]:
#Aim: missing value treatment

In [3]:
# Name:Aditi Ganvir
# Roll no:20
# Sec:C
# Subject:DSS
# Date:

In [4]:
#importing the basic library
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\user'

In [7]:
os.chdir('C:\\Users\\user')

In [8]:
data=pd.read_csv("C:\\Users\\user\\OneDrive\\Desktop\\titanic-dataset.ipynb")

In [9]:
data

Empty DataFrame
Columns: [{"cells":[{"cell_type":"code", execution_count:1, id:"d58f5393", metadata:{"_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19", _uuid:"8f2839f25d086af736a60e9eeb907d3b93b6e0e5", execution:{"iopub.execute_input":"2023-04-16T08:48:01.239979Z", iopub.status.busy:"2023-04-16T08:48:01.239413Z", iopub.status.idle:"2023-04-16T08:48:01.276037Z", shell.execute_reply:"2023-04-16T08:48:01.27498Z"}, papermill:{"duration":0.054014, end_time:"2023-04-16T08:48:01.279341", exception:false, start_time:"2023-04-16T08:48:01.225327", status:"completed"}, tags:[]}, outputs:[{"name":"stdout", output_type:"stream", text:["/kaggle/input/titanic/train.csv\n", /kaggle/input/titanic/test.csv\n, /kaggle/input/titanic/gender_submission.csv\n]}], source:["# This Python 3 environment comes with many helpful analytics libraries installed\n", # It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python\n, # For example, here's several helpful packages to load\n, \n, import numpy as np # linear algebra\n, import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n, \n.1, # Input data files are available in the read-only \../input/\" directory\n", # For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n, \n.2, import os\n, for dirname, _, filenames in os.walk('/kaggle/input'):\n,     for filename in filenames:\n,         print(os.path.join(dirname, filename))\n, \n.3, # You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \Save & Run All\" \n", # You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session]}, {"cell_type":"code", execution_count:2, id:"6c3ad595", metadata:{"execution":{"iopub.execute_input":"2023-04-16T08:48:01.305547Z", iopub.status.busy:"2023-04-16T08:48:01.304785Z", iopub.status.idle:"2023-04-16T08:48:02.494362Z", shell.execute_reply:"2023-04-16T08:48:02.492775Z"}, papermill:{"duration":1.205193, end_time:"2023-04-16T08:48:02.497409", exception:false.1, start_time:"2023-04-16T08:48:01.292216", status:"completed"}.1, tags:[]}.1, outputs:[], source:["import pandas as pd\n", import numpy as np\n, import matplotlib.pyplot as plt\n, %matplotlib inline\n, import seaborn as sns]}, {"cell_type":"code".1, execution_count:3, id:"1af1a0d7", metadata:{"execution":{"iopub.execute_input":"2023-04-16T08:48:02.520416Z", iopub.status.busy:"2023-04-16T08:48:02.519979Z", iopub.status.idle:"2023-04-16T08:48:02.560428Z", shell.execute_reply:"2023-04-16T08:48:02.559187Z"}, papermill:{"duration":0.055416, end_time:"2023-04-16T08:48:02.563184", exception:false.2, start_time:"2023-04-16T08:48:02.507768", status:"completed"}.2, tags:[]}.2, outputs:[].1, source:["train= pd.read_csv(\"/kaggle/input/titanic/train.csv\")\n", test = pd.read_csv(\/kaggle/input/titanic/test.csv\")\n", submission_gender = pd.read_csv(\/kaggle/input/titanic/gender_submission.csv\")"]}, {"cell_type":"code".2, execution_count:4, id:"190b4d86", metadata:{"execution":{"iopub.execute_input":"2023-04-16T08:48:02.587302Z", iopub.status.busy:"2023-04-16T08:48:02.586858Z", iopub.status.idle:"2023-04-16T08:48:02.620334Z", shell.execute_reply:"2023-04-16T08:48:02.619119Z"}, papermill:{"duration":0.048976, end_time:"2023-04-16T08:48:02.622903", exception:false.3, start_time:"2023-04-16T08:48:02.573927", status:"completed"}.3, tags:[]}.3, outputs:[{"data":{"text/html":["<div>\n", <style scoped>\n,     .dataframe tbody tr th:only-of-type {\n,         vertical-align: middle;\n,     }\n, \n.4,     .dataframe tbody tr th {\n,         vertical-align: top;\n,     }\n.1, \n.5,     .dataframe thead th {\n,         text-align: right;\n,     }\n.2, </style>\n, ...]
Index: []

[0 rows x 1798 columns]

In [10]:
data.describe()

,"{""cells"":[{""cell_type"":""code""",execution_count:1,"id:""d58f5393""","metadata:{""_cell_guid"":""b1076dfc-b9ad-4769-8c92-a6c4dae69d19""","_uuid:""8f2839f25d086af736a60e9eeb907d3b93b6e0e5""","execution:{""iopub.execute_input"":""2023-04-16T08:48:01.239979Z""","iopub.status.busy:""2023-04-16T08:48:01.239413Z""","iopub.status.idle:""2023-04-16T08:48:01.276037Z""","shell.execute_reply:""2023-04-16T08:48:01.27498Z""}","papermill:{""duration"":0.054014",...,"version:""2.4.0""}","kaggle:{""accelerator"":""none""","dataSources:[{""sourceType"":""competition""",sourceId:3136}],isInternetEnabled:true,"language:""python"".1","sourceType:""notebook""",isGpuEnabled:false}},nbformat:4,nbformat_minor:5}
count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
unique,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
data.shape

(0, 1798)

In [12]:
data.size

0

In [13]:
data.ndim

2

# Finding Missing Values

In [14]:
# check Missing Value by record 

data.isna()

Empty DataFrame
Columns: [{"cells":[{"cell_type":"code", execution_count:1, id:"d58f5393", metadata:{"_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19", _uuid:"8f2839f25d086af736a60e9eeb907d3b93b6e0e5", execution:{"iopub.execute_input":"2023-04-16T08:48:01.239979Z", iopub.status.busy:"2023-04-16T08:48:01.239413Z", iopub.status.idle:"2023-04-16T08:48:01.276037Z", shell.execute_reply:"2023-04-16T08:48:01.27498Z"}, papermill:{"duration":0.054014, end_time:"2023-04-16T08:48:01.279341", exception:false, start_time:"2023-04-16T08:48:01.225327", status:"completed"}, tags:[]}, outputs:[{"name":"stdout", output_type:"stream", text:["/kaggle/input/titanic/train.csv\n", /kaggle/input/titanic/test.csv\n, /kaggle/input/titanic/gender_submission.csv\n]}], source:["# This Python 3 environment comes with many helpful analytics libraries installed\n", # It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python\n, # For example, here's several helpful packages to load\n, \n, import numpy as np # linear algebra\n, import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n, \n.1, # Input data files are available in the read-only \../input/\" directory\n", # For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n, \n.2, import os\n, for dirname, _, filenames in os.walk('/kaggle/input'):\n,     for filename in filenames:\n,         print(os.path.join(dirname, filename))\n, \n.3, # You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \Save & Run All\" \n", # You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session]}, {"cell_type":"code", execution_count:2, id:"6c3ad595", metadata:{"execution":{"iopub.execute_input":"2023-04-16T08:48:01.305547Z", iopub.status.busy:"2023-04-16T08:48:01.304785Z", iopub.status.idle:"2023-04-16T08:48:02.494362Z", shell.execute_reply:"2023-04-16T08:48:02.492775Z"}, papermill:{"duration":1.205193, end_time:"2023-04-16T08:48:02.497409", exception:false.1, start_time:"2023-04-16T08:48:01.292216", status:"completed"}.1, tags:[]}.1, outputs:[], source:["import pandas as pd\n", import numpy as np\n, import matplotlib.pyplot as plt\n, %matplotlib inline\n, import seaborn as sns]}, {"cell_type":"code".1, execution_count:3, id:"1af1a0d7", metadata:{"execution":{"iopub.execute_input":"2023-04-16T08:48:02.520416Z", iopub.status.busy:"2023-04-16T08:48:02.519979Z", iopub.status.idle:"2023-04-16T08:48:02.560428Z", shell.execute_reply:"2023-04-16T08:48:02.559187Z"}, papermill:{"duration":0.055416, end_time:"2023-04-16T08:48:02.563184", exception:false.2, start_time:"2023-04-16T08:48:02.507768", status:"completed"}.2, tags:[]}.2, outputs:[].1, source:["train= pd.read_csv(\"/kaggle/input/titanic/train.csv\")\n", test = pd.read_csv(\/kaggle/input/titanic/test.csv\")\n", submission_gender = pd.read_csv(\/kaggle/input/titanic/gender_submission.csv\")"]}, {"cell_type":"code".2, execution_count:4, id:"190b4d86", metadata:{"execution":{"iopub.execute_input":"2023-04-16T08:48:02.587302Z", iopub.status.busy:"2023-04-16T08:48:02.586858Z", iopub.status.idle:"2023-04-16T08:48:02.620334Z", shell.execute_reply:"2023-04-16T08:48:02.619119Z"}, papermill:{"duration":0.048976, end_time:"2023-04-16T08:48:02.622903", exception:false.3, start_time:"2023-04-16T08:48:02.573927", status:"completed"}.3, tags:[]}.3, outputs:[{"data":{"text/html":["<div>\n", <style scoped>\n,     .dataframe tbody tr th:only-of-type {\n,         vertical-align: middle;\n,     }\n, \n.4,     .dataframe tbody tr th {\n,         vertical-align: top;\n,     }\n.1, \n.5,     .dataframe thead th {\n,         text-align: right;\n,     }\n.2, </style>\n, ...]
Index: []

[0 rows x 1798 columns]

In [15]:
# check Missing Value by columns

data.isna().any()

{"cells":[{"cell_type":"code"                                    False
execution_count:1                                                False
id:"d58f5393"                                                    False
metadata:{"_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19"    False
_uuid:"8f2839f25d086af736a60e9eeb907d3b93b6e0e5"                 False
                                                                 ...
language:"python".1                                              False
sourceType:"notebook"                                            False
isGpuEnabled:false}}                                             False
nbformat:4                                                       False
nbformat_minor:5}                                                False
Length: 1798, dtype: bool

In [16]:
# check Missing Value by columnswith Count

data.isna().sum()

{"cells":[{"cell_type":"code"                                    0
execution_count:1                                                0
id:"d58f5393"                                                    0
metadata:{"_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19"    0
_uuid:"8f2839f25d086af736a60e9eeb907d3b93b6e0e5"                 0
                                                                ..
language:"python".1                                              0
sourceType:"notebook"                                            0
isGpuEnabled:false}}                                             0
nbformat:4                                                       0
nbformat_minor:5}                                                0
Length: 1798, dtype: int64

# Missing Values Tretment

In [17]:
df1=data.fillna(data.mean())

In [18]:
# check Missing Value by columnswith Count

df1.isna().sum()

{"cells":[{"cell_type":"code"                                    0
execution_count:1                                                0
id:"d58f5393"                                                    0
metadata:{"_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19"    0
_uuid:"8f2839f25d086af736a60e9eeb907d3b93b6e0e5"                 0
                                                                ..
language:"python".1                                              0
sourceType:"notebook"                                            0
isGpuEnabled:false}}                                             0
nbformat:4                                                       0
nbformat_minor:5}                                                0
Length: 1798, dtype: int64

# 2nd Method

In [19]:
df2=data["Age"].fillna(29.699118)

KeyError: 'Age'

In [ ]:
# check Missing Value by columnswith Count

df2.isna().sum()

# 3rd Method

In [ ]:
df3=data.dropna()

In [ ]:
df3

In [ ]:
df3.isna().sum()